### ISSUE TITLE
Feature Request: Personal Social Media Details Display

### ISSUE THREAD

**Issue by AldairAvelino** [Alexandre-Gaspar/Gerador-de-link-de-redes-sociais#1]
Hey there,

I noticed that your product currently lacks the functionality to display personal social media details. Integrating this feature would greatly enhance user engagement and provide a more personalized experience for your users.

1. Benefits:

    - Enhanced Connectivity: Users can connect more easily with you outside the platform, fostering a sense of community.
    - Improved Networking: Facilitates networking among users with you, potentially leading to increased user retention.

Your attention to this feature request would contribute to the overall improvement of the product.

> Let me know if you need any further clarification or assistance in the implementation process.

**Comment by Alexandre-Gaspar** [comment]
Hey, I'm well
Thank you for your attention on this little project of mine. 
I will take your comment into consideration and improve the project.

**Comment by AldairAvelino** [comment]
I am glad for hearing that
